from __future__ import annotations
from pathlib import Path
import html
import re
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
RECIPES_DIR = ROOT / 'recipes'
DOCS_DIR = ROOT / 'docs'

STYLE = """/* Generated by scripts/generate_site.py */
:root {
  --bg: #faf7f2;
  --surface: #fffdf9;
  --surface-strong: #fff4df;
  --border: #e6dccb;
  --text: #2a241d;
  --muted: #64584a;
  --accent: #b65c1c;
  --accent-soft: #f7dfc7;
  --success: #30563a;
  --shadow: 0 18px 40px rgba(58, 37, 18, 0.08);
  --radius: 18px;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: linear-gradient(180deg, #fffaf2 0%, var(--bg) 100%);
  color: var(--text);
  line-height: 1.6;
}
a { color: var(--accent); }
a:hover { color: #8e4512; }
.container {
  width: min(1100px, calc(100% - 2rem));
  margin: 0 auto;
}
header.hero {
  padding: 4rem 0 2.5rem;
}
.hero-panel, .panel {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}
.hero-panel {
  padding: 2rem;
  display: grid;
  gap: 1rem;
}
.badge {
  display: inline-flex;
  width: fit-content;
  padding: 0.3rem 0.75rem;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
  font-weight: 700;
  font-size: 0.92rem;
}
h1, h2, h3 { line-height: 1.2; margin-top: 0; }
h1 { font-size: clamp(2rem, 4vw, 3.6rem); margin-bottom: 0.75rem; }
h2 { font-size: clamp(1.5rem, 3vw, 2rem); }
.lead { font-size: 1.1rem; color: var(--muted); max-width: 70ch; }
.grid {
  display: grid;
  gap: 1rem;
}
.summary-grid {
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  margin: 1.5rem 0 0;
}
.summary-grid > div {
  padding: 1rem;
  background: var(--surface-strong);
  border: 1px solid var(--border);
  border-radius: 14px;
}
.recipe-grid {
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  padding-bottom: 3rem;
}
.recipe-card {
  padding: 1.2rem;
  display: grid;
  gap: 0.8rem;
}
.recipe-card p { margin: 0; color: var(--muted); }
.recipe-card .meta, .recipe-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.chip {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.28rem 0.7rem;
  border-radius: 999px;
  background: #f8efe4;
  color: #6a461f;
  font-size: 0.9rem;
}
.button {
  display: inline-flex;
  width: fit-content;
  align-items: center;
  justify-content: center;
  padding: 0.8rem 1rem;
  border-radius: 12px;
  text-decoration: none;
  background: var(--accent);
  color: white;
  font-weight: 700;
}
.button.secondary {
  background: transparent;
  color: var(--accent);
  border: 1px solid var(--border);
}
main.page {
  padding: 0 0 3rem;
}
.two-col {
  display: grid;
  gap: 1rem;
  grid-template-columns: minmax(0, 1.2fr) minmax(280px, 0.8fr);
}
.panel {
  padding: 1.35rem;
}
ul, ol { padding-left: 1.2rem; }
li + li { margin-top: 0.45rem; }
.callout {
  padding: 1rem;
  border-radius: 14px;
  border: 1px solid var(--border);
  background: #fff8ee;
}
.callout.success {
  background: #eef8ef;
  color: var(--success);
  border-color: #c9decf;
}
footer {
  padding: 0 0 3rem;
  color: var(--muted);
}
.breadcrumbs {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  font-size: 0.95rem;
  margin-bottom: 1rem;
}
@media (max-width: 840px) {
  .two-col { grid-template-columns: 1fr; }
}
"""

BEAN_GUIDE = {
    'beans': [
        'Measure the dry beans. A good beginner amount is 1 cup dry beans, which makes about 2 to 3 cups cooked beans.',
        'Pour the beans onto a plate or baking sheet and quickly look for tiny stones or damaged beans. Throw those away.',
        'Rinse the beans in a colander under cool water.',
        'Soak overnight if you have time: put the beans in a bowl, cover with plenty of water, and leave them 8 to 12 hours. Drain before cooking. If you forget, you can skip soaking, but the beans will usually take longer to cook.',
        'To cook on the stove, put the soaked or unsoaked beans in a pot and cover with 2 inches of fresh water. Bring to a boil, then lower to a gentle simmer.',
        'Cook until tender. Black beans usually take about 60 to 90 minutes after soaking; white beans are often similar; older beans can take longer.',
        'Add salt near the end if you want more control over texture. The beans are ready when you can mash one easily with a fork.',
        'Drain the cooked beans and cool them. Store them in the refrigerator for up to 4 days or freeze in 1/2-cup portions for quick breakfasts.'
    ],
    'chickpeas': [
        'Pick through the dry chickpeas and rinse them well.',
        'Soak them overnight in plenty of water. Chickpeas expand a lot, so use a large bowl.',
        'Drain, transfer to a pot, and cover with fresh water by about 2 inches.',
        'Bring to a boil, lower to a simmer, and cook until very tender. This usually takes about 60 to 90 minutes on the stove after soaking.',
        'Taste one. It should be creamy inside, not chalky or crunchy.',
        'Drain and cool. Freeze extra chickpeas in 1/2-cup bags or containers so future breakfasts are much easier.'
    ],
    'lentils': [
        'Lentils are easier than most dried beans because they usually do not need soaking.',
        'Spread the lentils on a plate and look for small stones or wrinkled lentils, then rinse well.',
        'Put 1 cup lentils and 3 cups water in a pot. Bring to a boil, then lower to a gentle simmer.',
        'Cook until tender. Brown or green lentils usually take 20 to 35 minutes; red lentils cook faster and become soft and creamy.',
        'Drain any extra liquid if needed. Lentils should be soft enough to bite easily without crunching.'
    ]
}

METHOD_OVERRIDES = {
    'smoothie': ('blender', ['blender', 'measuring cup', 'spoon']),
    'pudding': ('no-cook', ['jar or bowl', 'spoon']),
    'overnight oats': ('no-cook', ['jar or bowl', 'spoon']),
    'toast': ('toast', ['toaster or skillet', 'small bowl', 'fork', 'knife']),
    'burrito': ('burrito', ['skillet or microwave', 'spoon', 'plate']),
    'waffles': ('waffles', ['blender', 'waffle iron', 'measuring cups']),
    'muffins': ('bake', ['mixing bowl', 'muffin tin', 'fork or whisk']),
    'bake': ('bake', ['mixing bowl', 'baking dish', 'fork or whisk']),
    'bars': ('bake', ['mixing bowl', 'baking pan', 'spoon']),
    'omelet': ('omelet', ['nonstick skillet', 'spatula', 'bowl', 'fork']),
    'hard-boiled': ('boil-eggs', ['small saucepan', 'slotted spoon', 'bowl']),
    'poached': ('poach-eggs', ['saucepan', 'slotted spoon', 'small bowl']),
    'skillet': ('skillet', ['skillet', 'spatula', 'knife', 'cutting board']),
    'scramble': ('skillet', ['skillet', 'spatula', 'bowl', 'fork']),
    'porridge': ('simmer', ['small pot', 'spoon', 'measuring cups']),
    'oatmeal': ('simmer', ['small pot', 'spoon', 'measuring cups']),
    'barley': ('simmer', ['small pot', 'spoon', 'measuring cups']),
    'buckwheat': ('simmer', ['small pot', 'spoon', 'measuring cups']),
    'quinoa': ('simmer', ['small pot', 'spoon', 'measuring cups']),
    'cereal': ('assemble', ['bowl', 'spoon']),
    'plate': ('assemble', ['knife', 'plate', 'small bowl'])
}


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')


def parse_recipe(path: Path) -> dict:
    text = path.read_text()
    _, front, body = text.split('---', 2)
    day = int(re.search(r'day: (\d+)', front).group(1))
    name = re.search(r'name: "([^"]+)"', front).group(1)
    servings = re.search(r'servings: (\d+)', front)
    servings = int(servings.group(1)) if servings else 1
    ingredients = []
    current = None
    for line in front.splitlines():
        item_match = re.match(r'\s*- item: "([^"]+)"', line)
        if item_match:
            if current:
                ingredients.append(current)
            current = {'item': item_match.group(1)}
            continue
        if current is not None:
            q = re.match(r'\s+quantity: "([^"]+)"', line)
            u = re.match(r'\s+unit: "([^"]+)"', line)
            if q:
                current['quantity'] = q.group(1)
            elif u:
                current['unit'] = u.group(1)
    if current:
        ingredients.append(current)
    short = []
    for line in body.splitlines():
        m = re.match(r'\d+\.\s+(.*)', line.strip())
        if m:
            short.append(m.group(1))
    tags = re.findall(r'-\s+([a-z-]+)', body.split('## Shopping Tags')[-1]) if '## Shopping Tags' in body else []
    filename = f"recipe-{day:02d}-{slugify(name)}.html"
    return {
        'day': day,
        'name': name,
        'servings': servings,
        'ingredients': ingredients,
        'short_instructions': short,
        'tags': tags,
        'filename': filename,
        'path': path,
    }


def fmt_ingredient(ing: dict) -> str:
    q = ing.get('quantity', '').strip()
    u = ing.get('unit', '').strip()
    item = ing['item']
    if q and u:
        return f"{q} {u} {item}"
    if q:
        return f"{q} {item}"
    return item


def detect_method(recipe: dict) -> tuple[str, list[str]]:
    text = recipe['name'].lower()
    for key, value in METHOD_OVERRIDES.items():
        if key in text:
            return value
    return 'assemble', ['bowl', 'spoon', 'plate']


def has_word(recipe: dict, *words: str) -> bool:
    combined = recipe['name'].lower() + ' ' + ' '.join(i['item'].lower() for i in recipe['ingredients'])
    return any(word in combined for word in words)


def ingredient_note(recipe: dict) -> list[str]:
    notes = []
    if has_word(recipe, 'frozen berries', 'berries', 'strawberries', 'blueberries', 'banana'):
        notes.append('If you are using frozen fruit, you do not need to thaw it for hot oatmeal or smoothies. For toast or bowls, thaw just enough so it is easy to eat.')
    if has_word(recipe, 'avocado'):
        notes.append('A ripe avocado should give slightly when you press the skin. If it feels rock hard, leave it on the counter for another day or two.')
    if has_word(recipe, 'egg', 'eggs', 'egg white'):
        notes.append('Crack eggs on a flat counter, not on the bowl edge. This reduces shell pieces and keeps the yolk more intact.')
    if has_word(recipe, 'tofu'):
        notes.append('If the tofu looks very wet, wrap it in paper towels and gently press for 5 to 10 minutes so the final dish tastes less watery.')
    if has_word(recipe, 'quinoa', 'barley', 'buckwheat', 'oats'):
        notes.append('Grains are done when they taste tender, not crunchy. If the pan looks dry before the grains soften, add a splash more water.')
    if has_word(recipe, 'sweet potato'):
        notes.append('If you are starting with a raw sweet potato, cut it into small cubes, toss with a little oil, and roast at 425°F until fork-tender, usually 20 to 30 minutes.')
    if has_word(recipe, 'asparagus', 'bell peppers', 'mushroom', 'spinach', 'kale'):
        notes.append('Cut vegetables into small, similar pieces so they soften at the same speed and are easier to chew in a breakfast dish.')
    return notes


def before_you_start(recipe: dict, equipment: list[str]) -> list[str]:
    items = [
        f"Set out your equipment first: {', '.join(equipment)}.",
        'Read every step one time before you turn on the heat so nothing feels rushed.',
        'Wash produce, dry it if needed, and measure ingredients into small bowls or cups before cooking.'
    ]
    if has_word(recipe, 'beans', 'chickpeas', 'lentils'):
        items.append('If your recipe uses cooked beans, chickpeas, or lentils, decide whether you are using canned legumes or cooking a batch from dry pantry staples first.')
    return items


def generate_steps(recipe: dict, method: str) -> list[str]:
    name = recipe['name'].lower()
    ingredients = [i['item'].lower() for i in recipe['ingredients']]
    steps = []
    if method == 'no-cook':
        steps = [
            'Put all measured ingredients into a jar or bowl large enough for stirring without spilling.',
            'Stir slowly, scraping the bottom and sides, until the seeds or oats are evenly coated and no dry pockets remain.',
            'Let the mixture sit for 5 minutes, then stir again. This second stir breaks up clumps and helps everything thicken evenly.',
            'Cover and chill if the recipe is meant to be overnight, or let it stand on the counter until thick if it is a quick pudding.',
            'Taste before serving and add a tiny splash of liquid if the mixture became thicker than you like.'
        ]
    elif method == 'toast':
        steps = [
            'Toast the bread until the surface is crisp and lightly browned. If you do not own a toaster, warm the bread in a dry skillet over medium heat and flip once.',
            'While the bread toasts, prepare the topping in a small bowl. Mash avocado, beans, or other spreadable ingredients with a fork until they are easy to spread.',
            'If the recipe includes an egg, cook it while the bread finishes. Use medium heat so the egg cooks gently instead of burning.',
            'Spread the topping over the hot toast all the way to the edges so each bite has flavor.',
            'Finish with seasonings, fruit, or crunchy toppings and serve right away so the toast stays crisp.'
        ]
    elif method == 'burrito':
        steps = [
            'Warm the filling first. Cold beans or vegetables make the burrito feel heavy and can tear the tortilla.',
            'Heat the tortilla for 10 to 20 seconds in the microwave or a dry skillet so it becomes flexible.',
            'Place the tortilla on a plate and arrange the filling in a short line slightly below the center. Do not overfill it.',
            'Fold the left and right sides inward, then roll from the bottom upward while tucking the filling in tightly.',
            'If you want a firmer burrito, place it seam-side down in a dry skillet for 1 to 2 minutes so it lightly toasts and holds together.'
        ]
    elif method == 'bake':
        steps = [
            'Preheat the oven before mixing so it is fully hot when the batter or filling is ready.',
            'Grease the pan lightly or line it with parchment if you have it. This helps the food release without sticking.',
            'Mix wet ingredients first, then stir in dry ingredients just until combined. Overmixing can make baked breakfasts dense.',
            'Transfer the mixture to the pan and spread it into an even layer so it bakes at the same rate all over.',
            'Bake until the center looks set and the edges are lightly browned. Let it rest for several minutes before slicing so it firms up.'
        ]
    elif method == 'waffles':
        steps = [
            'Preheat the waffle iron fully. Most waffle irons cook better when they are completely hot before batter goes in.',
            'Blend or whisk the batter until smooth, then let it sit for 2 to 3 minutes so bubbles settle and dry ingredients hydrate.',
            'Grease the waffle iron lightly if your model tends to stick.',
            'Pour in enough batter to cover most of the grid without overflowing, then close the lid and let the waffle cook until the iron signals or steam decreases a lot.',
            'Lift the waffle out gently with a fork or silicone tool and let it rest for 1 minute before topping so it stays crisp.'
        ]
    elif method == 'omelet':
        steps = [
            'Beat the eggs in a bowl with a fork until the yolks and whites look fully combined and slightly frothy.',
            'Heat a nonstick skillet over medium-low heat and add a little oil or butter. The pan should feel hot but not smoke.',
            'Cook any vegetables first until they soften. Wet vegetables can tear an omelet if they are added raw.',
            'Pour in the eggs and let them sit briefly, then use a spatula to gently pull cooked egg from the edges toward the center.',
            'When the top still looks a little moist but not raw, add fillings to one half and fold the omelet over. Rest for 30 to 60 seconds before sliding onto a plate.'
        ]
    elif method == 'boil-eggs':
        steps = [
            'Place the eggs in a saucepan and cover them with cold water by about 1 inch.',
            'Bring the water just to a boil, then turn off the heat, cover the pan, and let the eggs stand for about 10 to 12 minutes.',
            'Transfer the eggs to cold water or an ice bath so they stop cooking and become easier to peel.',
            'Tap each egg gently all over, then peel under running water if bits of shell stick.',
            'Serve whole, halved, or sliced with the rest of the meal.'
        ]
    elif method == 'poach-eggs':
        steps = [
            'Fill a saucepan with a few inches of water and bring it to a gentle simmer. You want small bubbles, not a hard boil.',
            'Crack each egg into a small bowl first. This makes it easier to slide the egg into the water without breaking the yolk.',
            'Stir the water once to create a gentle swirl, then lower the bowl close to the water and slide the egg in carefully.',
            'Cook until the whites are set and the yolk is as runny or firm as you like, usually about 3 to 4 minutes.',
            'Lift the egg out with a slotted spoon and let extra water drip off before placing it on the finished base.'
        ]
    elif method == 'skillet':
        steps = [
            'Heat the skillet over medium heat before adding oil. A warmed pan helps food cook evenly.',
            'Add sturdy ingredients first, such as onion, mushrooms, or sweet potato, because they take longer to soften.',
            'When vegetables are partly cooked, add quicker ingredients such as spinach, cooked beans, tofu, or eggs.',
            'Stir often enough to prevent burning, but not constantly. Letting food sit for a moment can improve browning and flavor.',
            'Taste a small bite before serving and adjust with salt, pepper, or other seasonings.'
        ]
    elif method == 'simmer':
        steps = [
            'Bring the water or milk to a gentle boil, then lower the heat so the pot simmers instead of violently bubbling.',
            'Stir in the grains slowly while stirring. This reduces clumping and helps the texture stay even.',
            'Cook on low to medium-low heat, stirring every few minutes and scraping the bottom of the pot so nothing sticks.',
            'If the mixture becomes thicker than expected before the grains soften, add a splash of hot water and keep cooking.',
            'When the grains are tender, turn off the heat, cover the pot, and let it sit for 2 to 5 minutes. This short rest improves texture.'
        ]
    else:  # assemble
        steps = [
            'Set all of the ingredients on the counter and prepare anything that needs slicing, mashing, or thawing first.',
            'Build the meal in the order that makes eating easiest: base first, protein next, and toppings last.',
            'Taste as you go so you can add extra seasoning, acidity, or sweetness before serving.',
            'Wipe the edges of the bowl or plate if needed. A tidy plate makes simple food feel more inviting.',
            'Serve immediately, especially if crunchy components are involved.'
        ]

    if has_word(recipe, 'lentils') and method == 'poach-eggs':
        steps = [
            'Rinse the lentils and oats if needed, then put them in a pot with water or broth. Bring to a boil and lower to a simmer.',
            'Cook until the lentils and oats are both tender, stirring occasionally so the mixture does not stick. Add a splash of water if it gets too thick before softening.',
            'Season the porridge and keep it warm on low heat while you poach the egg in a separate pan or after the porridge is done.',
            'Poach the egg in gently simmering water until the white is set and the yolk is cooked to your liking.',
            'Spoon the porridge into a bowl, place the egg on top, and finish with any herbs, pepper, or other toppings.'
        ]
    if has_word(recipe, 'chickpea') and 'toast' in name:
        steps = [
            'If you are using canned chickpeas, drain and rinse them. If you cooked them from dry, make sure they are fully tender before starting the scramble.',
            'Warm a skillet over medium heat with a little oil, then add the chickpeas and any vegetables or seasonings. Mash some of the chickpeas lightly with a fork or spatula so the mixture feels more like scrambled filling than loose beans.',
            'Cook until the chickpeas are hot and the vegetables soften. Add a spoonful of water if the pan looks dry.',
            'Toast the bread while the scramble cooks so both parts finish at about the same time.',
            'Pile the chickpea mixture onto the toast and serve right away.'
        ]
    if 'mediterranean breakfast plate' in name:
        steps = [
            'Wash and slice any fresh vegetables or fruit first so the plate is easy to assemble once you start.',
            'Toast bread or warm any grain component if you want part of the plate served hot.',
            'Portion protein items such as yogurt, eggs, beans, or cheese into small piles or bowls instead of mixing everything together.',
            'Arrange the plate with larger items first, then tuck smaller items into open spaces. This keeps the plate neat and easy to eat.',
            'Add a final drizzle of olive oil, lemon, herbs, or seasoning and serve.'
        ]
    if 'cereal' in name:
        steps = [
            'Place the cereal in a bowl first so you can judge how much milk the bowl will comfortably hold.',
            'Pour in the soy milk slowly. Add less than you think at first because you can always add more.',
            'Slice banana or add fruit on top rather than under the cereal so it stays visible and is easier to eat.',
            'Stir just once or twice if you want every bite slightly coated, or leave it layered if you prefer crunch.',
            'Eat promptly so the cereal does not become soggy.'
        ]
    if 'smoothie bowl' in name:
        steps.append('Pour the thick smoothie into a bowl instead of a glass and add toppings only after blending so they stay crunchy.')
    if 'microwave egg in a cup' in name:
        steps = [
            'Grease a microwave-safe mug or bowl lightly so the egg releases more easily after cooking.',
            'Cut the vegetables into very small pieces so they soften during the short microwave time.',
            'Beat the egg in the mug with a fork until the color looks even, then stir in the vegetables and seasonings.',
            'Microwave in short bursts, stirring between bursts, until the egg is set but still moist. Short bursts prevent rubbery eggs.',
            'Let the mug stand for 1 minute before eating because microwaved eggs stay very hot after the microwave stops.'
        ]

    if 'microwave' in name:
        steps.insert(1, 'Use a microwave-safe mug or bowl that is larger than the ingredients. Eggs puff up as they cook, and extra space prevents overflow.')
    if 'smoothie' in name:
        steps = [
            'Add liquid to the blender first. This helps the blades move more easily once the frozen ingredients go in.',
            'Add soft ingredients next, then frozen fruit or ice last.',
            'Blend on low for a few seconds, then increase to high until smooth. Stop and scrape down the sides if pieces get stuck.',
            'If the smoothie is too thick to blend, add 1 to 2 tablespoons of liquid at a time instead of pouring in a lot at once.',
            'Taste before serving and adjust sweetness or thickness as needed.'
        ]
    return steps


def bean_section(recipe: dict) -> tuple[str, list[str]] | None:
    combined = recipe['name'].lower() + ' ' + ' '.join(i['item'].lower() for i in recipe['ingredients'])
    if 'lentil' in combined:
        return ('How to prepare lentils from dry pantry stock', BEAN_GUIDE['lentils'])
    if 'chickpea' in combined:
        return ('How to prepare chickpeas from dry pantry stock', BEAN_GUIDE['chickpeas'])
    if 'black bean' in combined or 'white bean' in combined or 'bean' in combined or 'beans' in combined:
        return ('How to prepare beans from dry pantry stock', BEAN_GUIDE['beans'])
    return None


def troubleshooting(recipe: dict) -> list[str]:
    tips = []
    if has_word(recipe, 'oats', 'barley', 'buckwheat', 'quinoa'):
        tips.append('Too thick: stir in a spoonful of hot water at a time until the texture loosens.')
    if has_word(recipe, 'smoothie', 'pudding', 'overnight'):
        tips.append('Too thick: add a small splash of milk or water and stir or blend again.')
    if has_word(recipe, 'beans', 'chickpeas', 'lentils'):
        tips.append('Legumes still tough: they simply need more cooking time. Simmer longer and check every 10 minutes.')
    if has_word(recipe, 'egg', 'eggs'):
        tips.append('Eggs browning too fast: lower the heat. Eggs cook better gently than quickly.')
    tips.append('Not flavorful enough: add a pinch of salt, a squeeze of lemon, or a dusting of your favorite spice blend.')
    return tips


def recipe_summary(recipe: dict) -> str:
    text = recipe['name'].lower()
    if 'smoothie' in text:
        return 'A fast blender breakfast with clear tips on texture, layering ingredients, and making frozen fruit work for you.'
    if 'burrito' in text:
        return 'A portable breakfast with simple rolling instructions and help for warming fillings so the tortilla does not tear.'
    if 'toast' in text:
        return 'A quick toast-based breakfast with guidance on ripeness, spreading, and timing eggs so everything is ready together.'
    if any(word in text for word in ['oat', 'porridge', 'barley', 'buckwheat', 'quinoa']):
        return 'A warm bowl-style breakfast with beginner-friendly stovetop instructions and texture cues to tell when grains are done.'
    if any(word in text for word in ['omelet', 'scramble', 'skillet', 'egg', 'muffins', 'bake', 'waffles']):
        return 'A cooked breakfast with step-by-step heat control and sequencing notes so each ingredient finishes at the right time.'
    return 'A straightforward breakfast recipe rewritten with extra detail for cooks who want everything explained clearly.'


def render_page(recipe: dict, recipes: list[dict]) -> str:
    method, equipment = detect_method(recipe)
    beginner_steps = generate_steps(recipe, method)
    notes = ingredient_note(recipe)
    preflight = before_you_start(recipe, equipment)
    bean = bean_section(recipe)
    trouble = troubleshooting(recipe)
    ingredients_html = ''.join(f'<li>{html.escape(fmt_ingredient(i))}</li>' for i in recipe['ingredients'])
    notes_html = ''.join(f'<li>{html.escape(n)}</li>' for n in notes)
    preflight_html = ''.join(f'<li>{html.escape(n)}</li>' for n in preflight)
    steps_html = ''.join(f'<li>{html.escape(s)}</li>' for s in beginner_steps)
    trouble_html = ''.join(f'<li>{html.escape(t)}</li>' for t in trouble)
    bean_html = ''
    if bean:
        bean_html = f"""
        <section class=\"panel\">
          <h2>{html.escape(bean[0])}</h2>
          <ol>{''.join(f'<li>{html.escape(step)}</li>' for step in bean[1])}</ol>
        </section>
        """
    nav_links = []
    idx = recipes.index(recipe)
    if idx > 0:
        prev = recipes[idx-1]
        nav_links.append(f'<a class="button secondary" href="{html.escape(prev["filename"])}">← Day {prev["day"]:02d}</a>')
    if idx < len(recipes)-1:
        nxt = recipes[idx+1]
        nav_links.append(f'<a class="button secondary" href="{html.escape(nxt["filename"])}">Day {nxt["day"]:02d} →</a>')
    nav_html = ''.join(nav_links)
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Day {recipe['day']:02d} · {html.escape(recipe['name'])}</title>
  <meta name=\"description\" content=\"Beginner-friendly instructions for {html.escape(recipe['name'])}.\" />
  <link rel=\"stylesheet\" href=\"styles.css\" />
</head>
<body>
  <header class=\"hero\">
    <div class=\"container\">
      <div class=\"hero-panel\">
        <div class=\"breadcrumbs\"><a href=\"index.html\">Home</a> <span>•</span> <span>Day {recipe['day']:02d}</span></div>
        <span class=\"badge\">Day {recipe['day']:02d}</span>
        <h1>{html.escape(recipe['name'])}</h1>
        <p class=\"lead\">{html.escape(recipe_summary(recipe))}</p>
        <div class=\"recipe-meta\">
          <span class=\"chip\">Serves {recipe['servings']}</span>
          <span class=\"chip\">Method: {html.escape(method.replace('-', ' '))}</span>
          <span class=\"chip\">Tags: {html.escape(', '.join(recipe['tags']) or 'breakfast')}</span>
        </div>
      </div>
    </div>
  </header>
  <main class=\"page\">
    <div class=\"container grid\">
      <div class=\"two-col\">
        <section class=\"panel\">
          <h2>Beginner-friendly instructions</h2>
          <ol>{steps_html}</ol>
        </section>
        <aside class=\"grid\">
          <section class=\"panel\">
            <h2>Ingredients</h2>
            <ul>{ingredients_html}</ul>
          </section>
          <section class=\"panel\">
            <h2>Equipment</h2>
            <ul>{''.join(f'<li>{html.escape(item)}</li>' for item in equipment)}</ul>
          </section>
        </aside>
      </div>
      <section class=\"panel\">
        <h2>Before you start</h2>
        <ul>{preflight_html}</ul>
      </section>
      <section class=\"panel\">
        <h2>Ingredient notes</h2>
        <ul>{notes_html or '<li>This is a forgiving recipe. Prepare the ingredients before heating anything, and adjust seasoning at the end.</li>'}</ul>
      </section>
      <section class=\"panel\">
        <h2>Original recipe card summary</h2>
        <ol>{''.join(f'<li>{html.escape(step)}</li>' for step in recipe['short_instructions']) or '<li>This recipe card was very short, so the page above expands it into clearer steps.</li>'}</ol>
      </section>
      {bean_html}
      <section class=\"panel\">
        <h2>If something goes wrong</h2>
        <ul>{trouble_html}</ul>
      </section>
      <section class=\"panel callout success\">
        <h2>Make-ahead and leftovers</h2>
        <p>Most cooked grains, beans, and chopped fruit can be prepared ahead. Store leftovers in covered containers. If texture changes after chilling, add a splash of water or milk and warm or stir again before eating.</p>
      </section>
      <div>{nav_html}</div>
    </div>
  </main>
  <footer>
    <div class=\"container\">Built as a static site for GitHub Pages from the breakfast recipe cards in this repository.</div>
  </footer>
</body>
</html>
"""


def render_index(recipes: list[dict]) -> str:
    cards = []
    for recipe in recipes:
        card = f"""
        <article class=\"panel recipe-card\">
          <span class=\"badge\">Day {recipe['day']:02d}</span>
          <h2>{html.escape(recipe['name'])}</h2>
          <p>{html.escape(recipe_summary(recipe))}</p>
          <div class=\"meta\">
            <span class=\"chip\">Serves {recipe['servings']}</span>
            <span class=\"chip\">{html.escape(', '.join(recipe['tags']) or 'breakfast')}</span>
          </div>
          <a class=\"button\" href=\"{html.escape(recipe['filename'])}\">Open recipe</a>
        </article>
        """
        cards.append(card)
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Breakfast Recipe Cards</title>
  <meta name=\"description\" content=\"A GitHub Pages-friendly breakfast recipe site with one page per recipe and beginner-friendly instructions.\" />
  <link rel=\"stylesheet\" href=\"styles.css\" />
</head>
<body>
  <header class=\"hero\">
    <div class=\"container\">
      <div class=\"hero-panel\">
        <span class=\"badge\">GitHub Pages-ready</span>
        <h1>Breakfast recipes with beginner-friendly guidance</h1>
        <p class=\"lead\">This site turns the repository's breakfast plan into a simple static website. Every recipe has its own page, and bean-based meals explain how to start from dry beans, chickpeas, or lentils instead of assuming canned shortcuts.</p>
        <div class=\"summary-grid\">
          <div><strong>30 recipe pages</strong><br/>One dedicated HTML page for each breakfast recipe.</div>
          <div><strong>Clear cooking cues</strong><br/>Instructions describe what "done" looks like so nervous cooks can check texture and heat.</div>
          <div><strong>Dry bean help</strong><br/>Legume recipes include basic sorting, soaking, simmering, and storage guidance.</div>
        </div>
      </div>
    </div>
  </header>
  <main class=\"page\">
    <div class=\"container grid\">
      <section class=\"panel\">
        <h2>Using the site</h2>
        <ul>
          <li>Start with any day below and open the recipe page.</li>
          <li>Read the <strong>Before you start</strong> section before you heat anything.</li>
          <li>For bean, chickpea, or lentil breakfasts, use the pantry-stock section on that recipe page if you are beginning with dry legumes.</li>
        </ul>
      </section>
      <section class=\"panel callout\">
        <h2>Quick dry-legume cheat sheet</h2>
        <ul>
          <li><strong>Beans:</strong> sort, rinse, soak 8 to 12 hours if possible, then simmer until tender.</li>
          <li><strong>Chickpeas:</strong> soak overnight, then simmer until creamy inside.</li>
          <li><strong>Lentils:</strong> usually no soaking required; rinse and simmer until soft.</li>
        </ul>
      </section>
      <section>
        <h2>All recipes</h2>
        <div class=\"grid recipe-grid\">{''.join(cards)}</div>
      </section>
    </div>
  </main>
  <footer>
    <div class=\"container\">Publish the <code>docs/</code> folder with GitHub Pages to host this site.</div>
  </footer>
</body>
</html>
"""


def update_root_readme() -> None:
    readme = ROOT / 'README.md'
    original = readme.read_text().rstrip() + '\n\n'
    note = '## Website\n\nA simple GitHub Pages-ready website is available in [`docs/`](./docs/) with a separate page for every recipe card and beginner-friendly cooking guidance. Open [`docs/index.html`](./docs/index.html) locally or publish the `docs/` folder with GitHub Pages.\n'
    if '## Website' not in original:
        readme.write_text(original + note)


def main() -> None:
    recipes = [parse_recipe(p) for p in sorted(RECIPES_DIR.glob('day-*.md'))]
    DOCS_DIR.mkdir(exist_ok=True)
    (DOCS_DIR / 'styles.css').write_text(STYLE)
    (DOCS_DIR / 'index.html').write_text(render_index(recipes))
    for recipe in recipes:
        (DOCS_DIR / recipe['filename']).write_text(render_page(recipe, recipes))
    update_root_readme()
    print(f'Generated {len(recipes)} recipe pages plus index into {DOCS_DIR}')

if __name__ == '__main__':
    main()
